micronaut:
  application:
    name: userNEW3
  http:
    client:
      read-timeout: 30s
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/khusbu
    username: khusbu
    password: postgres
    driverClassName: org.postgresql.Driver
karza:
  api:
    key: EALKBXrX5NuFSqHW
    base-url: "https://testapi.karza.in/"